{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-job
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  selector:
    matchLabels:
      job-name: {{ .Release.Name }}-migrate-job
  template:
    metadata:
      labels:
        job-name: {{ .Release.Name }}-migrate-job
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "db:deploy"]
          # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
          # ★ このenvセクションを、.env.localに合わせて修正します ★
          # ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
          env:
            # --- データベース接続情報 ---
            - name: PG_USER
              value: "user" # .env.localの値
            - name: PG_DB_NAME
              value: "mydatabase" # .env.localの値
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  # ★ {{ .Release.Name }} を使って動的にする
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: DATABASE_URL
              # ★ PG_USERとPG_DB_NAMEを使うように修正
              value: "postgresql://$(PG_USER):$(PG_PASSWORD)@{{ .Release.Name }}-postgresql:5432/$(PG_DB_NAME)?schema=public"
  backoffLimit: 1
{{- end }}