{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-job
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  selector:
    matchLabels:
      job-name: {{ .Release.Name }}-migrate-job
  template:
    metadata:
      labels:
        job-name: {{ .Release.Name }}-migrate-job
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
           # ★★★★★ ここを command と args に修正 ★★★★★
          command: ["/bin/sh", "-c"]
          args: 
            - |
              export DATABASE_URL="postgresql://$(PG_USER):$(PG_PASSWORD)@{{ .Release.Name }}-postgresql:5432/$(PG_DB_NAME)?schema=public"
              exec npm run db:deploy

          env:
            # PG_USER, PG_DB_NAME, PG_PASSWORD の定義は変更なし
            - name: PG_USER
              value: "user"
            - name: PG_DB_NAME
              value: "mydatabase"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            # DATABASE_URL の定義は command に移動したため削除
  backoffLimit: 1
{{- end }}