{{- if .Values.app.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.releaseName }}-{{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "next.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.app.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "next.selectorLabels" . | nindent 6 }}
{{- end }}
