# -------------------
# PostgreSQL用 Secret
# -------------------
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.releaseName }}-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "password" # .env.localのPOSTGES_PASSWORD

---